# Generated by Django 4.1.3 on 2022-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(default='', upload_to='blog/img')),
                ('category', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
