# Generated by Django 4.1.3 on 2022-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('World', 'World'), ('US', 'US'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Science', 'Science'), ('Health', 'Health'), ('Travel', 'Travel')], max_length=255, null=True),
        ),
    ]
